name: CI

on: push

jobs:
    DEPLOY:
        runs-on:  ubuntu-latest
        steps:
            - name: Get-Repository-Copy
              uses: actions/checkout@v2
              
            - name: Content-1
              run: ls
              
            - name: BUILD
              run: |
                docker build -t cv -f Dockerfile .
              
            - name: View
              run: docker ps -a
              
            - name: Images
              run: docker images
              
            - name: RUN
              #uses: ./
              run: docker run cv

            - name: Content-2
              run: ls
