name: CI

on: push

jobs:
    DEPLOY:
        runs-on:  ubuntu-latest
        steps:
            - name: Get-Repository-Copy
              uses: actions/checkout@v2
              
            - name: Content-1
              run: ls
              
            - name: BUILD
              run: |
                docker build -t cv -f Dockerfile .
              
            - name: Content-2
              run: ls
              
            - name: RUN
              uses: ./
              id: cv

            - name: Content-3
              run: ls
